'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { statusLines, registryLines } = require('../docs/status/status_manifest.js');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/status_manifest.json')));
const registry = JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/research_status_registry.json')));
const lines = statusLines(manifest);
assert.strictEqual(lines.length, 9);
assert(lines.some(line => line.includes('R4/R4b') && line.endsWith('FAIL')));
const components = registryLines(registry);
assert(components.some(line => line.includes('P10') && line.includes('COMPLETED / INCONCLUSIVE')));
assert(components.some(line => line.includes('D8B') && line.includes('COMPLETED / MATERIAL_LOSS')));
assert(components.some(line => line.includes('SAM_IN_SIM') && line.includes('ARCHIVED_WITHDRAWN')));
assert(components.some(line => line.includes('BEARING_DEG') && line.includes('BLOCKED')));
assert(components.some(line => line.includes('LIVE_RGB_POLICY') && line.includes('NOT_TESTED')));
assert(components.some(line => line.includes('TM_E2') && line.includes('POLICY_COMPARISON_NOT_TESTED')));
assert.throws(() => statusLines({...manifest, real_flight_validated: true}));
assert.throws(() => registryLines({...registry, schema_version: 2}));
console.log('Public status manifest: PASS');
