#!/usr/bin/env python3
"""Render the human-readable quantitative positioning document from the ledger.

Numbers are never typed into the document by hand. They are rendered from
`docs/literature_quantitative_ledger_2026-09-18.json` (external, Layer A) and
`docs/quantitative_positioning_registry.json` (MOTAR's own, Layer B), so the
prose cannot drift from the recorded provenance.

    python3 tools/build_literature_positioning_doc.py            # write
    python3 tools/build_literature_positioning_doc.py --check    # verify current
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "docs/literature_quantitative_ledger_2026-09-18.json"
REGISTRY = ROOT / "docs/quantitative_positioning_registry.json"
OUT = ROOT / "docs/literature_quantitative_positioning_2026-09-18.md"

HEADER = """# Quantitative positioning across published systems — 2026-09-18

**Reported numbers · not head-to-head.**

These values are reported under each publication's own benchmark. They are not subtracted from
MOTAR results. Class A matched external comparisons remain **zero**.

This document is generated by `tools/build_literature_positioning_doc.py` from
[`literature_quantitative_ledger_2026-09-18.json`](literature_quantitative_ledger_2026-09-18.json)
and [`quantitative_positioning_registry.json`](quantitative_positioning_registry.json). Do not edit
it by hand; edit the ledger and regenerate. `tests/test_quantitative_positioning.py` binds every
MOTAR number to the result file it cites and rejects cross-benchmark comparative wording.

## How to read this

Three layers, and only one of them would ever license a comparison.

* **Layer A — published context.** What each system reported, under its own arena, sensors, task and
  success definition. Useful for knowing what conditions the field reports under. Not comparable.
* **Layer B — MOTAR internal evidence.** MOTAR's own measured effects, each bound to a result path.
  These are within-repository matched-baseline contrasts.
* **Layer C — matched external comparison.** Same arena, layouts, start states, target trajectory,
  success definition, timeout, seeds and episode count. **Currently empty.**

A value of `NOT_EXTRACTED` means the source did not state the number in text the verification could
read — most often because the result exists only as a plotted curve, or the paper is paywalled. It
does **not** mean the system performs poorly, and it must never be filled in by estimation.

"""

FOOTER = """
## Why no cross-system subtraction appears anywhere

Every system above differs from MOTAR in at least one contract-defining way, and usually several:
the input representation (privileged relative state versus sensor-only observation), the number of
agents, the capture or success definition, the arena, the obstacle model, and whether the target is
scripted, cooperative, marked, or absent entirely. Subtracting percentages across those boundaries
would produce a number with no defined meaning.

The honest form of positioning is the one used here: record what each work measured, record what
MOTAR measured, and keep the matched-comparison layer explicitly empty until a preregistered port
fills it. `docs/external_matched_baseline_readiness_2026-09-18.md` assesses which candidates could
be ported, selected on benchmark compatibility rather than on expected outcome.
"""


def fmt_value(value, unit):
    if value == "NOT_EXTRACTED":
        return "`NOT_EXTRACTED`"
    if isinstance(value, dict):
        inner = "; ".join(f"{k} {v}" for k, v in value.items())
        return f"{inner}" + (f" {unit}" if unit else "")
    if isinstance(value, list):
        inner = "–".join(str(v) for v in value)
        return f"{inner}" + (f" {unit}" if unit else "")
    return f"{value}" + (f" {unit}" if unit else "")


def render() -> str:
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    out = [HEADER]

    entries = ledger["entries"]
    works, order = {}, []
    for entry in entries:
        works.setdefault(entry["work"], []).append(entry)
        if entry["work"] not in order:
            order.append(entry["work"])

    n_num = sum(1 for e in entries if e["value"] != "NOT_EXTRACTED")
    n_ne = sum(1 for e in entries if e["value"] == "NOT_EXTRACTED")
    by_type = {}
    for e in entries:
        by_type[e["source_type"]] = by_type.get(e["source_type"], 0) + 1

    retained = [w for w in order
                if any(e.get("retained_in_site_table", True) for e in works[w])]
    not_retained = [w for w in order if w not in retained]
    out.append("## Layer A — published context\n")
    out.append(f"{len(order)} works, {len(entries)} recorded rows: **{n_num}** carrying a value and "
               f"**{n_ne}** recorded as `NOT_EXTRACTED`. By source: "
               + ", ".join(f"{k} {v}" for k, v in sorted(by_type.items())) + ".\n")
    out.append(f"\n{len(retained)} of these works populate the site's ten retained rows — NavRL/NavRL++ "
               "share one row and YOPO/YOPOv2-Tracker share another, so twelve works occupy ten rows. "
               + (f"{len(not_retained)} work ({', '.join(not_retained)}) was screened but is not "
                  "retained in the site table; it appears here because it holds a result its "
                  "retained sibling does not.\n" if not_retained else "\n"))

    for work in order:
        rows = works[work]
        out.append(f"\n### {work}\n")
        url = rows[0]["source_url"]
        out.append(f"Source: <{url}> · version/state read: {rows[0]['paper_version_date']} · "
                   f"comparability class **{rows[0]['comparison_class']}** · "
                   f"benchmark parity with MOTAR: **no**\n")
        out.append("\n| Metric | Reported | Conditions | Sim/real | Trials | Where |")
        out.append("|---|---|---|---|---|---|")
        for r in rows:
            cond = f"{r['task']}; target: {r['target_type']}; sensor: {r['sensor']}; speed: {r['speed_condition']}"
            trials = r.get("trials_or_episodes") or "—"
            out.append(
                f"| {r['metric']} | {fmt_value(r['value'], r.get('unit'))} | {cond} | "
                f"{r['simulation_or_real']} | {trials} | {r['source_section']} ({r['source_type']}) |")
        out.append("")
        for r in rows:
            out.append(f"* **{r['metric']}** — {r['allowed_interpretation']}")
        out.append("")

    out.append("\n## Layer B — MOTAR internal evidence\n")
    out.append("Each row is a within-repository matched-baseline contrast, bound to the result file "
               "it cites. `pp` means percentage points.\n")
    out.append("| Research axis | Baseline | Treatment | Measured effect | Verdict | Source |")
    out.append("|---|---|---|---|---|---|")
    for m in registry["internal_motar"]:
        if m["verdict"] == "RESULT_PENDING":
            effect = "—"
            src = "—"
        else:
            bits = []
            for key, suffix in (("value_pp", " pp"), ("value_percent", " %"), ("value_utility", " utility")):
                if m.get(key) is not None:
                    bits.append(f"{m[key]:+g}{suffix}" if key != "value_percent" else f"{m[key]:g}{suffix}")
            if m.get("secondary_value_pp") is not None:
                bits.append(f"capture {m['secondary_value_pp']:+g} pp")
            if m.get("ci95_pp"):
                lo, hi = m["ci95_pp"]
                bits.append(f"95% CI [{lo:+g}, {hi:+g}] pp")
            if m.get("extra"):
                bits.append(m["extra"])
            effect = "; ".join(bits)
            src = f"[`{Path(m['source_path']).parent.name}`]({'../' + m['source_path']})"
        out.append(f"| {m['axis']} | {m['baseline']} | {m['treatment']} | {effect} | "
                   f"**{m['verdict']}** | {src} |")
    out.append("")
    for m in registry["internal_motar"]:
        out.append(f"* **{m['axis']}** — {m['limitation']}")

    matched = registry["matched_external"]
    out.append("\n## Layer C — matched external comparison\n")
    out.append(f"**Class A count: {matched['class_a_count']}.** {matched['note']}\n")
    out.append(FOOTER)
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists():
            print(f"missing {OUT}", file=sys.stderr)
            return 2
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is stale; regenerate with {Path(__file__).name}", file=sys.stderr)
            return 2
        print("positioning document is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
