"""Test whether the Sony5100 calibration candidate, cam0's surveyed position, drone0's GT trajectory and the
frame timestamps are mutually consistent, using HUMAN-reviewed drone0 boxes.

Two independent estimates are computed from reviewed box centres:
  * rotation-only fit (camera position fixed at the surveyed cam0 location; Kabsch on bearing rays)
  * unconstrained PnP whose recovered camera centre is compared with the surveyed position
Frame-time alignments from -3 to +3 frames are evaluated and reported, because the published stamps were
generated by MATLAB VideoReader (CurrentTime after readFrame, edit list of one frame, one frame fewer than the
container) with sync coefficients that were later revised upstream.

The search is deliberately wider than the frame-count ambiguity. A mismatch that is a frame-index
relabelling lands on an integer shift; one that does not is a timing offset between the published stamps
and the pose, which no relabelling can fix. The continuous optimum is refined and reported so the two are
never confused.

Reading the winning shift: the review images were rendered at `container_index = frame_id + offset`
(the pilot receipt's `container_index_offset`). If the true mapping is `container_index = frame_id + d`,
the consistent alignment is `shift = offset - d`, so `d = offset - shift`. With offset 0, a winning shift
of 0 means the edit-list candidate is right, +1 means the reader dropped the last frame instead.
Thresholds are fixed here BEFORE any box exists; the tool never edits boxes.
"""
import argparse
import csv
import json
import math
from pathlib import Path

from prepare_eth_ds5 import COMMIT, digests, numeric_table, write_json
from prepare_eth_ds5_review import interpolate_pose

def true_index_offset(container_index_offset, winning_shift):
    """Recover the frame_id -> container index offset d from the alignment shift that fitted."""
    return container_index_offset - winning_shift


def refine_shift(evaluator, coarse_best, span=1.0, steps=41, rounds=3):
    """Continuous minimum of the pixel RMS around the best integer shift.

    An optimum that does not sit on an integer cannot be a frame-index relabelling, so the caller must
    not report an index offset for it.
    """
    lo, hi, best = coarse_best - span, coarse_best + span, None
    for _ in range(rounds):
        for i in range(steps):
            shift = lo + (hi - lo) * i / (steps - 1)
            value = evaluator(shift)
            if value is not None and (best is None or value < best[1]):
                best = (shift, value)
        if best is None:
            return None
        step = (hi - lo) / (steps - 1)
        lo, hi = best[0] - step, best[0] + step
    return {"shift_frames": best[0], "pixel_rms": best[1],
            "distance_to_nearest_integer_frames": abs(best[0] - round(best[0])),
            "is_integer_relabelling": abs(best[0] - round(best[0])) <= INTEGER_TOLERANCE_FRAMES}


PIXEL_RMS_PASS = 4.0        # px, 1080p; box-centre noise plus 1 cm GT is well below this
CENTRE_DISTANCE_PASS = 2.0  # m between PnP centre and the surveyed cam0 position
MIN_BOXES = 6
ALIGNMENT_SHIFTS = tuple(range(-8, 9))
INTEGER_TOLERANCE_FRAMES = 0.2


def load_review(path):
    rows = []
    with open(path, newline="") as handle:
        for r in csv.DictReader(handle):
            if r.get("drone0_visible", "").strip().lower() not in ("yes", "y", "1", "true"):
                continue
            box = [float(r["box_x1"]), float(r["box_y1"]), float(r["box_x2"]), float(r["box_y2"])]
            if box[2] <= box[0] or box[3] <= box[1]:
                raise ValueError("degenerate box for frame " + r["frame_id"])
            rows.append({"frame_id": int(r["frame_id"]), "opencv_index": int(r["opencv_index"]),
                         "project_timestamp_s": float(r["project_timestamp_s"]), "box_xyxy": box,
                         "centre": [(box[0] + box[2]) / 2, (box[1] + box[3]) / 2]})
    return rows


def valid_distortion_radius(dist):
    """Largest normalized image radius where the Brown-Conrady radial model is still injective.

    r_d(r) = r(1 + k1 r^2 + k2 r^4 + k3 r^6) stops increasing once its derivative changes sign; beyond
    that radius the model folds back and a point far outside the field of view projects to a plausible
    in-image pixel, while undistortPoints inverts it onto the wrong branch. Points past this radius must
    never be scored: a wrong identity or alignment could otherwise be rewarded by the fold.
    """
    import numpy as np
    k1, k2, p1, p2, k3 = (list(dist) + [0.0] * 5)[:5]
    # derivative in u = r^2: 1 + 3 k1 u + 5 k2 u^2 + 7 k3 u^3
    roots = np.roots([7 * k3, 5 * k2, 3 * k1, 1.0]) if k3 else (
        np.roots([5 * k2, 3 * k1, 1.0]) if k2 else np.roots([3 * k1, 1.0]) if k1 else [])
    positive = [r.real for r in np.atleast_1d(roots) if abs(getattr(r, "imag", 0.0)) < 1e-9 and r.real > 0]
    return math.sqrt(min(positive)) if positive else float("inf")


def alignment_discrimination(pose, camera, times, period, focal):
    """Image displacement, in pixels, that one frame of timing error produces.

    Computed from the angle between the ground-truth bearing at t and at t+period, scaled by the focal
    length, so it needs no camera orientation. It is the discriminating power of the alignment search:
    when it is not clearly larger than box-centre annotation noise, neighbouring shifts fit almost
    equally well and the alignment cannot be resolved however good the best fit looks.
    """
    displacement = []
    for t in times:
        a, b = interpolate_pose(pose, t), interpolate_pose(pose, t + period)
        if a is None or b is None:
            continue
        rays = []
        for sample in (a, b):
            v = [sample["xyz_m"][i] - camera[i] for i in range(3)]
            norm = math.sqrt(sum(c * c for c in v))
            rays.append([c / norm for c in v])
        cosine = max(-1.0, min(1.0, sum(x * y for x, y in zip(*rays))))
        displacement.append(focal * math.acos(cosine))
    if not displacement:
        return {"frames": 0}
    displacement.sort()
    return {"frames": len(displacement), "median_px": displacement[len(displacement) // 2],
            "min_px": displacement[0], "max_px": displacement[-1],
            "note": "pixels of image motion per frame of timing error; the alignment search can only"
                    " separate neighbouring shifts when this exceeds box-centre annotation noise"}


def camera_rays(pixels, K, dist):
    import cv2
    import numpy as np
    pts = np.asarray(pixels, np.float64).reshape(-1, 1, 2)
    norm = cv2.undistortPoints(pts, np.asarray(K, np.float64), np.asarray(dist, np.float64)).reshape(-1, 2)
    rays = np.concatenate([norm, np.ones((len(norm), 1))], axis=1)
    return rays / np.linalg.norm(rays, axis=1, keepdims=True)


def fit_rotation(rays_cam, rays_world):
    """Kabsch: R minimising sum ||R w - c||^2 over unit rays; returns R (world->camera) and residual degrees."""
    import numpy as np
    c, w = np.asarray(rays_cam), np.asarray(rays_world)
    u, _, vt = np.linalg.svd(c.T @ w)
    d = np.sign(np.linalg.det(u @ vt))
    R = u @ np.diag([1, 1, d]) @ vt
    cosines = np.clip(np.sum((w @ R.T) * c, axis=1), -1, 1)
    return R, np.degrees(np.arccos(cosines))


def reproject(R, camera_xyz, world_points, K, dist):
    import cv2
    import numpy as np
    rvec, _ = cv2.Rodrigues(np.asarray(R, np.float64))
    tvec = -np.asarray(R, np.float64) @ np.asarray(camera_xyz, np.float64)
    pixels, _ = cv2.projectPoints(np.asarray(world_points, np.float64).reshape(-1, 1, 3), rvec, tvec,
                                  np.asarray(K, np.float64), np.asarray(dist, np.float64))
    return pixels.reshape(-1, 2)


def pnp_centre(world_points, pixels, K, dist):
    import cv2
    import numpy as np
    ok, rvec, tvec = cv2.solvePnP(np.asarray(world_points, np.float64).reshape(-1, 1, 3),
                                  np.asarray(pixels, np.float64).reshape(-1, 1, 2),
                                  np.asarray(K, np.float64), np.asarray(dist, np.float64), flags=cv2.SOLVEPNP_SQPNP)
    if not ok:
        raise ValueError("PnP failed")
    R, _ = cv2.Rodrigues(rvec)
    return (-R.T @ tvec.reshape(3)).tolist()


def evaluate(reviewed, pose, camera_xyz, K, dist, period, alignment_shift_frames, image_size=None):
    import numpy as np
    world, pixels, used = [], [], []
    for r in reviewed:
        gt = interpolate_pose(pose, r["project_timestamp_s"] + alignment_shift_frames * period)
        if gt is None:
            continue
        world.append(gt["xyz_m"])
        pixels.append(r["centre"])
        used.append(r["frame_id"])
    if len(world) < MIN_BOXES:
        return {"status": "INSUFFICIENT_REVIEWED_BOXES", "boxes_used": len(world)}
    rays_c = camera_rays(pixels, K, dist)
    rays_w = np.asarray(world) - np.asarray(camera_xyz)
    rays_w = rays_w / np.linalg.norm(rays_w, axis=1, keepdims=True)
    R, angular = fit_rotation(rays_c, rays_w)
    # A point behind the fitted camera still projects to a finite, plausible-looking pixel, so it must be
    # rejected explicitly: no reviewer can have boxed a target that the camera could not see.
    depth = (np.asarray(world) - np.asarray(camera_xyz)) @ np.asarray(R, np.float64).T
    behind = int((depth[:, 2] <= 0).sum())
    if behind:
        return {"status": "POINTS_BEHIND_FITTED_CAMERA", "boxes_used": len(world), "frame_ids": used,
                "points_behind_camera": behind, "angular_residual_deg_max": float(angular.max()),
                "note": "the reviewed boxes cannot all come from one pinhole view at the surveyed position;"
                        " identity, alignment or the surveyed position is wrong"}
    radius = np.linalg.norm(depth[:, :2] / depth[:, 2:3], axis=1)
    limit = valid_distortion_radius(dist)
    if float(radius.max()) >= limit:
        return {"status": "POINTS_OUTSIDE_VALID_DISTORTION_RADIUS", "boxes_used": len(world), "frame_ids": used,
                "max_normalized_radius": float(radius.max()), "valid_radius_limit": limit,
                "angular_residual_deg_max": float(angular.max()),
                "note": "at least one ground-truth point falls where the radial model folds back, so its"
                        " projection is not trustworthy and the fit must not be scored"}
    projected = reproject(R, camera_xyz, world, K, dist)
    if image_size is not None:
        width, height = image_size
        outside = int(((projected[:, 0] < 0) | (projected[:, 0] > width) |
                       (projected[:, 1] < 0) | (projected[:, 1] > height)).sum())
    else:
        outside = None
    residual = projected - np.asarray(pixels)
    rms = float(math.sqrt(np.mean(np.sum(residual ** 2, axis=1))))
    centre = pnp_centre(world, pixels, K, dist)
    centre_distance = float(np.linalg.norm(np.asarray(centre) - np.asarray(camera_xyz)))
    passed = rms < PIXEL_RMS_PASS and centre_distance < CENTRE_DISTANCE_PASS
    return {"status": "CONSISTENT" if passed else "INCONSISTENT", "boxes_used": len(world), "frame_ids": used,
            "points_behind_camera": 0, "reprojections_outside_image": outside,
            "max_normalized_radius": float(radius.max()), "valid_radius_limit": limit,
            "rotation_world_to_camera": np.asarray(R).tolist(), "angular_residual_deg_max": float(angular.max()),
            "pixel_rms": rms, "pixel_residual_max": float(np.abs(residual).max()),
            "pnp_camera_centre_m": centre, "pnp_centre_distance_to_surveyed_m": centre_distance,
            "thresholds": {"pixel_rms": PIXEL_RMS_PASS, "centre_distance_m": CENTRE_DISTANCE_PASS}}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--review-csv", type=Path, required=True)
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--calibration", type=Path, required=True)
    parser.add_argument("--fps", type=float, default=30000 / 1001)
    parser.add_argument("--container-index-offset", type=int, default=None,
                        help="the pilot receipt's container_index_offset; when given, each consistent alignment"
                             " is reported as the frame_id->container index offset d it implies")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists():
        raise ValueError("refusing existing output")
    calibration = json.loads(args.calibration.read_text())
    pose = numeric_table(args.dataset / "dataset5/pose/fused_pose.txt", 11)
    camera_lines = (args.dataset / "dataset5/camera-locations/campos.txt").read_text().splitlines()
    camera = next(list(map(float, l.split()[1:])) for l in camera_lines if l.startswith("cam0\t"))
    reviewed = load_review(args.review_csv)
    period = 1.0 / args.fps
    # Every shift must be scored on the identical frame set, otherwise a shift that silently drops a
    # frame at the edge of pose support would be compared against a different measurement.
    common = [r for r in reviewed
              if all(interpolate_pose(pose, r["project_timestamp_s"] + s * period) is not None
                     for s in ALIGNMENT_SHIFTS)]
    dropped = [r["frame_id"] for r in reviewed if r not in common]
    focal = (calibration["K-matrix"][0][0] + calibration["K-matrix"][1][1]) / 2
    discrimination = alignment_discrimination(pose, camera, [r["project_timestamp_s"] for r in common],
                                              period, focal)
    results = {"alignment_shift_%+d" % s: evaluate(common, pose, camera, calibration["K-matrix"],
                                                   calibration["distCoeff"], period, s,
                                                   calibration.get("resolution"))
               for s in ALIGNMENT_SHIFTS}
    for key, value in results.items():
        shift = int(key.rsplit("_", 1)[1])
        value["shift_frames"] = shift
        if args.container_index_offset is not None:
            value["implied_container_index_offset_d"] = true_index_offset(args.container_index_offset, shift)
    def score(shift):
        outcome = evaluate(common, pose, camera, calibration["K-matrix"], calibration["distCoeff"],
                           period, shift, calibration.get("resolution"))
        return outcome.get("pixel_rms")

    consistent = sorted(k for k, v in results.items() if v["status"] == "CONSISTENT")
    scored = {k: v["pixel_rms"] for k, v in results.items() if "pixel_rms" in v}
    ranked = sorted(scored, key=scored.get)
    best = ranked[0] if ranked else None
    margin = scored[ranked[1]] - scored[ranked[0]] if len(ranked) > 1 else None
    refined = refine_shift(score, results[best]["shift_frames"]) if best else None
    at_edge = bool(best and abs(results[best]["shift_frames"]) == max(ALIGNMENT_SHIFTS))
    if at_edge:
        status = "SEARCH_RANGE_TOO_NARROW"
    elif not consistent:
        status = "CALIBRATION_CANDIDATE_NOT_VALIDATED"
    elif refined and not refined["is_integer_relabelling"]:
        status = "CALIBRATION_CONSISTENT_TIMING_OFFSET_NOT_A_RELABELLING"
    elif len(consistent) == 1:
        status = "CALIBRATION_CONSISTENT_ALIGNMENT_RESOLVED"
    else:
        status = "CALIBRATION_CONSISTENT_ALIGNMENT_AMBIGUOUS"
    receipt = {"status": status, "consistent_alignments": consistent, "source_commit": COMMIT,
               "reviewed_boxes": len(reviewed), "boxes_scored": len(common),
               "frames_dropped_for_common_pose_support": dropped,
               "best_alignment": best, "best_pixel_rms": scored.get(best),
               "runner_up_pixel_rms": scored[ranked[1]] if len(ranked) > 1 else None,
               "best_margin_px": margin,
               "implied_container_index_offset_d": (results[best].get("implied_container_index_offset_d")
                                                   if best and refined and refined["is_integer_relabelling"] else None),
               "refined_shift": refined,
               "refined_shift_ms": refined["shift_frames"] * period * 1000 if refined else None,
               "alignment_discrimination": discrimination,
               "review_csv_sha256": digests(args.review_csv)[1], "calibration_sha256": digests(args.calibration)[1],
               "results": results, "container_index_offset": args.container_index_offset,
               "tool_sha256": digests(Path(__file__))[1],
               "note": "Consistency of reviewed boxes with K/dist, the surveyed position and GT is necessary for"
                       " using the calibration; it does not certify lens distortion beyond the boxes tested."
                       " More than one consistent shift means the alignment is NOT resolved: the frames used do"
                       " not move enough between frames to separate them, so add fast segments before treating"
                       " any single mapping as established. A refined optimum away from an integer is a timing"
                       " offset, not a frame relabelling, and no index offset is reported for it."}
    write_json(args.output / "reprojection_check.json", receipt)
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
