#!/usr/bin/env python3
"""Generate the fresh v2 ref5in/target URDFs from provenance-frozen v1 sources."""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def transformed(source, destination, replacements, check=False):
    text = source.read_text(encoding="utf-8")
    for old, new, expected in replacements:
        count = text.count(old)
        if count != expected:
            raise RuntimeError(f"{source}: expected {expected} occurrences of {old!r}, found {count}")
        text = text.replace(old, new)
    if check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != text:
            raise RuntimeError(f"{destination}: generated bytes are stale")
    else:
        destination.write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated bytes without writing")
    args = parser.parse_args()
    robot_dir = ROOT / "resources/robots/quad"
    transformed(
        robot_dir / "quad_navrl_ref5in.urdf",
        robot_dir / "quad_navrl_ref5in_v2.urdf",
        [
            ("<robot name=\"quadrotor\">", "<robot name=\"quadrotor_ref5in_v2\">", 1),
            ("NavRL ref5in:", "NavRL ref5in v2:", 1),
            (
                "0.280 m numeric XY proxy, which under-bounds that span by 2.56 mm (0.91%). It is\n"
                "                 not an exact swept-prop hull and has not been validated against CAD.",
                "0.283 m conservative XY proxy. It rounds the 0.2825634 m derived span outward.\n"
                "                 It is not an exact swept-prop hull and has not been validated against CAD.",
                1,
            ),
            (
                "<!-- 0.28 m lineage XY proxy (0.91% below the assumed 0.2826 m tip span) x 0.12 m assumed height -->\n"
                "        <box size=\"0.28 0.28 0.12\"/>",
                "<!-- v2 rounds the 0.2826 m prop-tip span outward; 0.12 m height remains assumed. -->\n"
                "        <box size=\"0.283 0.283 0.12\"/>",
                1,
            ),
        ],
        check=args.check,
    )
    object_dir = ROOT / "resources/models/environment_assets/objects"
    transformed(
        object_dir / "navrl_target_drone.urdf",
        object_dir / "navrl_target_drone_v2.urdf",
        [
            ("<robot name=\"navrl_target_drone\">", "<robot name=\"navrl_target_drone_v2\">", 1),
            ("NavRL target rigid body.", "NavRL v2 target rigid body.", 1),
            ("0.28 x 0.28 x 0.12 m", "0.283 x 0.283 x 0.12 m", 1),
            ("<box size=\"0.28 0.28 0.12\"/>", "<box size=\"0.283 0.283 0.12\"/>", 2),
        ],
        check=args.check,
    )
    print(("verified" if args.check else "generated") + " ref5in v2 pursuer and target URDFs")


if __name__ == "__main__":
    main()
